http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: "localhost"
    paths: "/ip"
  
  posts:
    host: "localhost"
    paths: "/posts"

  comments:
    host: "localhost"
    paths: "/posts/:id/comments"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/apiEndpoints
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  
  postservice:
    url: "http://localhost:4000"

  commentservice:
    url: "http://localhost:4001"
  # see: http://www.express-gateway.io/docs/configuration/gateway.config.yml/serviceEndpoints
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
        - action:
            serviceEndpoint: httpbin
            changeOrigin: true

  
  postserviceApi:
    apiEndpoints:
      - posts
    policies:
      - proxy:
        - action:
            serviceEndpoint: postservice

  commentserviceApi:
    apiEndpoints:
      - comments
    policies:
      - proxy:
        - action: 
            serviceEndpoint: commentservice
  # see: https://www.express-gateway.io/docs/configuration/gateway.config.yml/pipelines
